Makefile: fix compile error for bpflist
  BINARY   biostacks
In file included from bpflist/bpflist.c:7:0:
./include/commons.h:16:10: fatal error: bpf/bpf.h: No such file or directory
 #include <bpf/bpf.h>
          ^~~~~~~~~~~
compilation terminated.

Fixes: b70136739385 ("Add bpflist support")
Signed-off-by: wolfgang huang <huangjinhui@kylinos.cn>
Change-Id: I11ee863d219a5a7d4db296888c22a3098a3e227d
Reviewed-on: http://gerrit.kylin.com/c/ketones/+/54726
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>