Revert "ksnoop: use bpf_get_func_ip() where helper is available"
This reverts commit 9ddb2edabedd28a5ce1cd5c378839924abbd7338.

Build in clang-10 with the following error:
ksnoop/ksnoop.bpf.c:97:7: error: use of unknown builtin '__builtin_preserve_enum_value' [-Wimplicit-function-declaration]
                    bpf_core_enum_value_exists(enum bpf_func_id, BPF_FUNC_get_func_ip)) {
                    ^
/home/tang/work/ketones/src/.output/bpf/bpf_core_read.h:216:2: note: expanded from macro 'bpf_core_enum_value_exists'
        __builtin_preserve_enum_value(*(typeof(enum_type) *)enum_value, BPF_ENUMVAL_EXISTS)

Signed-off-by: Youling Tang <tangyouling@kylinos.cn>
Change-Id: Ic24a6a881fc2125698251444c5323845b1ac82e6
Reviewed-on: http://gerrit.kylin.com/c/ketones/+/88905
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>